-- Query 1: Top 5 customers ranked by total spending
SELECT TOP 5
    c.customer_id,
    c.customer_name,
    c.city,
    SUM(o.order_amount) AS total_spent_inr
FROM dim_customers c
JOIN fct_orders o ON c.customer_id = o.customer_id
WHERE o.order_status = 'Delivered'
GROUP BY c.customer_id, c.customer_name, c.city
ORDER BY total_spent_inr DESC;

-- Query 2: Total revenue and orders by product category
SELECT 
    category,
    COUNT(order_id) AS total_orders,
    SUM(order_amount) AS total_revenue_inr
FROM fct_orders
WHERE order_status = 'Delivered'
GROUP BY category
ORDER BY total_revenue_inr DESC;

-- Query 3: Average order value (AOV) per payment method
SELECT 
    payment_method,
    COUNT(order_id) AS total_transactions,
    ROUND(AVG(order_amount), 2) AS avg_order_value_inr
FROM fct_orders
WHERE order_status = 'Delivered'
GROUP BY payment_method
ORDER BY avg_order_value_inr DESC;

-- Query 4: Total revenue generated by customer state
SELECT 
    c.state,
    COUNT(o.order_id) AS orders_count,
    SUM(o.order_amount) AS state_revenue_inr
FROM dim_customers c
JOIN fct_orders o ON c.customer_id = o.customer_id
WHERE o.order_status = 'Delivered'
GROUP BY c.state
ORDER BY state_revenue_inr DESC;

-- Query 5: Repeat customers who placed more than 1 delivered order
SELECT 
    c.customer_id,
    c.customer_name,
    COUNT(o.order_id) AS delivered_orders,
    SUM(o.order_amount) AS total_spent_inr
FROM dim_customers c
JOIN fct_orders o ON c.customer_id = o.customer_id
WHERE o.order_status = 'Delivered'
GROUP BY c.customer_id, c.customer_name
HAVING COUNT(o.order_id) > 1
ORDER BY total_spent_inr DESC;

-- Query 6: Monthly revenue trend for completed orders (Using standard YEAR & MONTH)
SELECT 
    YEAR(order_date) AS order_year,
    MONTH(order_date) AS order_month,
    COUNT(order_id) AS total_orders,
    SUM(order_amount) AS monthly_revenue_inr
FROM fct_orders
WHERE order_status = 'Delivered'
GROUP BY YEAR(order_date), MONTH(order_date)
ORDER BY order_year ASC, order_month ASC;

-- Query 7: High-value orders exceeding the overall average order value
SELECT 
    order_id,
    category,
    order_amount AS amount_inr
FROM fct_orders
WHERE order_status = 'Delivered' 
  AND order_amount > (SELECT AVG(order_amount) FROM fct_orders WHERE order_status = 'Delivered')
ORDER BY order_amount DESC;

-- Query 8: Overall order fulfillment rate (Delivered vs Cancelled)
SELECT 
    order_status,
    COUNT(order_id) AS order_count,
    ROUND(COUNT(order_id) * 100.0 / (SELECT COUNT(*) FROM fct_orders), 2) AS percentage
FROM fct_orders
GROUP BY order_status;

-- Query 9: Total volume and revenue from UPI payments
SELECT 
    payment_method,
    COUNT(order_id) AS total_upi_orders,
    SUM(order_amount) AS total_upi_revenue_inr
FROM fct_orders
WHERE payment_method = 'UPI' AND order_status = 'Delivered'
GROUP BY payment_method;

-- Query 10: High-value customers with lifetime spend exceeding ₹10,000
SELECT 
    c.customer_name,
    c.city,
    COUNT(o.order_id) AS total_orders,
    SUM(o.order_amount) AS total_spent_inr
FROM dim_customers c
JOIN fct_orders o ON c.customer_id = o.customer_id
WHERE o.order_status = 'Delivered'
GROUP BY c.customer_name, c.city
HAVING SUM(o.order_amount) > 10000.00
ORDER BY total_spent_inr DESC;